### GET all tankers
GET http://localhost:8080/webapi/tankers


### GET all tankers with params
GET http://localhost:8080/webapi/tankers?phrase=JohnSmith
custom-header: custom-value
Cookie: some-cookie=some-value


### Get tanker by id
GET http://localhost:8080/webapi/tankers/1
Accept: appplication/xml


### Get tankers of tank
GET http://localhost:8080/webapi/tanks/1/tankers
Accept: appplication/xml


### Create new tanker
POST http://localhost:8080/webapi/tankers/create-tanker
Content-Type: application/json
Accept-Language: en

{
  "name": "John",
  "surname": "Smith"
}



### Get all thanks
GET http://localhost:8080/webapi/tanks
Content-Type: application/json

{
  "name": "Tiger",
  "id": 1
}

### Get tank by id
GET http://localhost:8080/webapi/tanks/1

### Get tanks which are used by thankers
GET http://localhost:8080/webapi/tankers/1/tanks

### Create new thank
POST http://localhost:8080/webapi/tanks/create-tank
{
  "name": "test1"
  "tankers": "null"
  "plooton" : "null
}


